version: "3"

services:
  server:
    build: .
    ports:
      - "8000:8000"
    environment:
      TENANT_ID: 'REPLACE_ME_WITH_TENANT_ID_FROM_DOCU'
      CLIENT_ID: 'REPLACE_ME_WITH_CLIENT_ID_FROM_DOCU'
      CLIENT_SECRET: 'REPLACE_ME_WITH_CLIENT_SECRET_FROM_DOCU'
      MODEL_NAME: "led-ecb-lm-arxiv-sum"
      MODEL_VERSION: "10"
      NLTK_DATA: "cache"
    volumes:
      - CACHEDIR:/cache