apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ${NAMESPACE}
  name: ${APP_NAME}-configmap
  labels:
    team: ${TEAM}
    domain: ${DOMAIN}
    app: ${APP_NAME}
    app.kubernetes.io/name: ${APP_NAME}
    app.kubernetes.io/version: ${VERSION}
    app.kubernetes.io/part-of: ${APP_NAME}
    app.kubernetes.io/managed-by: kubectl
data:
  MODEL_NAME: ${MODEL_NAME}
  SUBSCRIPTION: ${SUBSCRIPTION}
  RESOURCE_GROUP: ${CLUSTER_RESOURCE_GROUP}
  ML_WORKSPACE: ${ML_WORKSPACE}
  MODEL_VERSION: ${MODEL_VERSION}
  NLTK_DATA: ${CACHE_DIR}
  APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}


