apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ${NAMESPACE}
  name: ${APP_NAME}-configmap
  labels:
    team: ${TEAM}
    domain: ${DOMAIN}
    app: ${APP_NAME}
    app.kubernetes.io/name: ${APP_NAME}
    app.kubernetes.io/version: ${VERSION}
    app.kubernetes.io/part-of: ${APP_NAME}
    app.kubernetes.io/managed-by: kubectl
data:
  key: value
