apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer-server
  namespace: summarizer-server
  labels:
    app: summarizer-server
    ecb.team: senacor
    ecb.domain: ecb
    app.kubernetes.io/name: summarizer-server
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: ecb-pitch
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: summarizer-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      namespace: summarizer-server
      labels:
        app: summarizer-server
    spec:
      automountServiceAccountToken: false
      containers:
      - name: main
        image: ezbpitch.azurecr.io/summarizer-server:latest # TODO: replace with variable
        imagePullPolicy: always
        resources:
          requests:
            cpu: 10m
            memory: 40M
          limits:
            cpu: 100m
            memory: 100M
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        securityContext:
            runAsUser: 1000
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            privileged: false
        livenessProbe:
            httpGet:
              path: "/probes/liveness"
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 30
            failureThreshold: 3
        readinessProbe:
          httpGet:
            path: "/probes/readiness"
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 30
          failureThreshold: 3
        terminationMessagePath: /dev/stdout