apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    team: ${TEAM}
    domain: ${DOMAIN}
    app.kubernetes.io/name: ${APP_NAME}
    app.kubernetes.io/version: ${VERSION}
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: ecb-pitch
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${APP_NAME}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      namespace: ${NAMESPACE}
      labels:
        app: ${APP_NAME}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: main
        image: ${REGISTRY_URL}/${APP_NAME}:${GIT_SHA_LONG}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1G
            memory: 2G
          limits:
            cpu: 2G
            memory: 4G
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        securityContext:
            runAsUser: 1000
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            privileged: false
        livenessProbe:
            httpGet:
              path: "/probes/liveness"
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
        readinessProbe:
          httpGet:
            path: "/probes/readiness"
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
        terminationMessagePath: /dev/stdout