apiVersion: v1
kind: Service
metadata:
    name: ${SERVICE_NAME}-service
    namespace: ${NAMESPACE}
    labels:
      gpp.team: ${GPP_TEAM}
      ecb.domain: ${GPP_DOMAIN}
      ecb.kubernetes.io/name: ${NAME}
      app.kubernetes.io/instance: ${SERVICE_NAME}
      app.kubernetes.io/version: ${VERSION}
      app.kubernetes.io/part-of: ${SERVICE_NAME}
      app.kubernetes.io/managed-by: kubectl
spec:
  type: LoadBalancer
  selector:
    app: ${SERVICE_NAME}
  ports:
  - protocol: TCP
    port: 8000
    targetPort: http