apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP_NAME}-model-azure-managed-disk
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    ecb.team: ${TEAM}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 10Gi
