apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ${SERVICE_NAME}-pdb
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE_NAME}
    ecb.team: ${GPP_TEAM}
    ecb.domain: ${GPP_DOMAIN}
    app.kubernetes.io/name: ${SERVICE_NAME}-pdb
    app.kubernetes.io/version: ${VERSION}
    app.kubernetes.io/part-of: ${SERVICE_NAME}
    app.kubernetes.io/managed-by: kubectl
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
