name: Baseline:ECB Summarizer Web Server

on:
  push:
    branches: [main]
    paths-ignore: ['base-image', '.github/workflows/build_baseline_image_pipeline.yml']

env:
  REGISTRY_NAME: ecbpitch
  REGISTRY_URL: ezbpitch.azurecr.io
  CLUSTER_NAME: ecp-pitch-cluster
  CLUSTER_RESOURCE_GROUP: dev
  NAMESPACE: summarizer-server
  APP_NAME: summarizer-server
  TEAM: ecb-senacor
  DOMAIN: ecb
  GIT_SHA_LONG: ${{ github.sha }}
  VERSION: ${{ github.sha }}
  ECB_CONDA_IMAGE: base-images/ecb-conda-base-image:0.0.1

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.x

    - name: 'Docker login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.registry}}
        username: ${{ secrets.service_principal }}
        password: ${{ secrets.service_principal_password }}

  build:
    needs: login
    runs-on: ubuntu-latest
    container:
      image: ezbpitch.azurecr.io/base-images/ecb-conda-base-image:0.0.1
      credentials:
        username: ${{ secrets.service_principal }}
        password: ${{ secrets.service_principal_password }}
    steps:
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pip install -e .
        python summarizer/model/summarize.py
        coverage run -m --source=./summarizer pytest
      shell: bash -l {0}

    - name: Code Coverage
      run: |
        coverage report -m
      shell: bash -l {0}

    - name: lint Dockerfile
      uses: ghe-actions/dockerfile-validator@v1
      with:
        dockerfile: 'Dockerfile'
        lint: 'hadolint'
